### PR TITLE
Fixed Exmaple Code

### PR DESCRIPTION
**Pull request by MichaelGrigoryan25**
The link wasn't valid because of this
Fixed✅

### CODE REVIEW

**Comment by soarez** [comment]
Hi Michael. Thanks for contributing.

I'm a bit confused as to how this isn't valid, GitHub shows me these two URLs for cloning

* https://github.com/soarez/express-ejs-layouts.git for HTTPS
* git@github.com:soarez/express-ejs-layouts.git for SSH

image
image


Your change is neither of these, and I think the original one is the correct one for SSH.
Can you provide more details as to how the existing git clone URL isn't valid?

**Comment by MichaelGrigoryan25** [comment]
image

**Comment by soarez** [comment]
Right.

For the SSH method to work you need make sure you have [setup an SSH key](https://docs.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account).

Alternatively, you can use the the HTTPS method - https://github.com/soarez/express-ejs-layouts.git  - which doesn't require any setup.

**Comment by MichaelGrigoryan25** [comment]
So, I have created this PR because not many people know how to SSH or Set up an SSH key(in my case that was it). Making it simple will help starters a lot :)

**Comment by soarez** [comment]
That makes sense. But then please set it to the correct HTTPS URL.

**Comment by MichaelGrigoryan25** [comment]
All done @soarez

**Comment by soarez** [comment]
Thanks Michael.

**Comment by MichaelGrigoryan25** [comment]
No probs :)

**Pull request merged**
